# Generated by Django 4.1.5 on 2023-01-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ("last_name",)},
        ),
        migrations.AlterField(
            model_name="remark",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_remarks",
                to="reports.student",
            ),
        ),
    ]
