# Generated by Django 4.1.5 on 2023-01-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_yearclass_remark_year_class"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="yearclass",
            options={"verbose_name_plural": "YearClass"},
        ),
    ]
