# Generated by Django 4.1.5 on 2023-01-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_alter_category_options_alter_yearclass_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yearclass",
            options={"ordering": ("name",), "verbose_name_plural": "YearClass"},
        ),
        migrations.RemoveField(
            model_name="remark",
            name="year_class",
        ),
        migrations.AddField(
            model_name="student",
            name="year_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.yearclass",
            ),
        ),
    ]
