# Generated by Django 4.1.5 on 2023-01-23 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_alter_yearclass_options_remove_remark_year_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="year_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_year_classes",
                to="reports.yearclass",
            ),
        ),
    ]
