# Generated by Django 4.1.7 on 2023-02-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_student_year_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
