# Generated by Django 4.1.7 on 2023-02-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0008_subject_teacher_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="subject",
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.ManyToManyField(blank=True, to="reports.subject"),
        ),
    ]
