# Generated by Django 4.1.7 on 2023-02-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0009_remove_teacher_subject_teacher_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="subject",
            field=models.ManyToManyField(blank=True, to="reports.subject"),
        ),
    ]
