# Generated by Django 4.1.7 on 2023-02-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0010_student_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="remark",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.subject",
            ),
        ),
    ]
