# Generated by Django 4.1.7 on 2023-02-26 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0011_remark_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="subject",
            new_name="subjects",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="subject",
            new_name="subjects",
        ),
    ]
